"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./ReactQueryProvider";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import Topnav from "@/components/Topnav";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  palette: {
    primary: { main: "#ADDFB3" }, //blue
    error: { main: "#D85F5F", light: "#F9BABA" }, //red, pink
    warning: { main: "#E1DCA7" }, //yellow
    success: { main: "#A5C9A5" }, //green
  },
  typography: {
    h1: {
      fontFamily: ["Rubik Doodle Shadow", "Vast Shadow", "Londrina Shadow"],
    },
    h2: { fontFamily: "Archivo Black" },
    h3: { fontFamily: "Archivo Black" },
    h4: { fontFamily: "Archivo Black" },
    h5: { fontFamily: "Archivo Black" },
    h6: { fontFamily: "Work Sans" },
    button: {
      fontFamily: "Paytone One",
      fontSize: "20px",
      color: "white",
      background: "#041E42 !important",
      transition: "none",
      transform: "none",
      borderRadius: "20px",
      width: "300px",
      disableRipple: true,
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <ThemeProvider theme={theme}>
          <body className={inter.className}>
            <Topnav />
            {children}
            <Footer />
          </body>
        </ThemeProvider>
      </html>
    </ReactQueryProvider>
  );
}
